<a href="https://colab.research.google.com/github/AndresMontesDeOca/Redes_Neuronales/blob/main/04_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
warnings.filterwarnings('ignore')


In [4]:
# !pip install ucimlrepo

In [10]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
image_segmentation = fetch_ucirepo(id=50)

# data (as pandas dataframes)
X = image_segmentation.data.features
y = image_segmentation.data.targets

data = pd.concat([X, y], axis=1)
data.to_csv('superficies.csv')

print(data.info())
display(data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   region-centroid-col   210 non-null    float64
 1   region-centroid-row   210 non-null    float64
 2   region-pixel-count    210 non-null    int64  
 3   short-line-density-5  210 non-null    float64
 4   short-line-density-2  210 non-null    float64
 5   vedge-mean            210 non-null    float64
 6   vedge-sd              210 non-null    float64
 7   hedge-mean            210 non-null    float64
 8   hedge-sd              210 non-null    float64
 9   intensity-mean        210 non-null    float64
 10  rawred-mean           210 non-null    float64
 11  rawblue-mean          210 non-null    float64
 12  rawgreen-mean         210 non-null    float64
 13  exred-mean            210 non-null    float64
 14  exblue-mean           210 non-null    float64
 15  exgreen-mean          2

region-centroid-col  region-centroid-row  region-pixel-count  \
0                140.0                125.0                   9   
1                188.0                133.0                   9   
2                105.0                139.0                   9   
3                 34.0                137.0                   9   
4                 39.0                111.0                   9   

   short-line-density-5  short-line-density-2  vedge-mean  vedge-sd  \
0                   0.0                   0.0    0.277778  0.062963   
1                   0.0                   0.0    0.333333  0.266667   
2                   0.0                   0.0    0.277778  0.107407   
3                   0.0                   0.0    0.500000  0.166667   
4                   0.0                   0.0    0.722222  0.374074   

   hedge-mean  hedge-sd  intensity-mean  rawred-mean  rawblue-mean  \
0    0.666667  0.311111        6.185185     7.333334      7.666666   
1    0.500000  0.077778        6.666666     8.333334      7.777778   
2    0.833333  0.522222        6.111111     7.555555      7.222222   
3    1.111111  0.474074        5.851852     7.777778      6.444445   
4    0.888889  0.429629        6.037037     7.000000      7.666666   

   rawgreen-mean  exred-mean  exblue-mean  exgreen-mean  value-mean  \
0       3.555556    3.444444     4.444445     -7.888889    7.777778   
1       3.888889    5.000000     3.333333     -8.333333    8.444445   
2       3.555556    4.333334     3.333333     -7.666666    7.555555   
3       3.333333    5.777778     1.777778     -7.555555    7.777778   
4       3.444444    2.888889     4.888889     -7.777778    7.888889   

   saturation-mean  hue-mean      class  
0         0.545635 -1.121818  BRICKFACE  
1         0.538580 -0.924817  BRICKFACE  
2         0.532628 -0.965946  BRICKFACE  
3         0.573633 -0.744272  BRICKFACE  
4         0.562919 -1.175773  BRICKFACE

In [55]:
# Paso 3: Separar características (X) y etiqueta (y)
X = data.iloc[:, :-1]  # Las primeras 19 columnas son características
y = data.iloc[:, -1]   # La última columna es la etiqueta

# Paso 4: Dividir el dataset en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, stratify=y)

# Paso 5: Estandarizar las características
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [56]:
MAX_ITER = 10000
COTA = 0.001
ALFA = 0.001
# cantidad de datos a procesar para actualizar pesos
TAM_LOTE = 50

ACTIVACION = 'relu'
#ACTIVACION = 'tanh'
#ACTIVATION = 'identity'

#OPTIMIZADOR = 'lbfgs'
OPTIMIZADOR = 'sgd'
# OPTIMIZADOR = 'adam'

mlpr = MLPClassifier(
    hidden_layer_sizes=[64, 32],  # Arquitectura con tres capas ocultas
    activation=ACTIVACION,  # Función de activación de capas ocultas.
    solver=OPTIMIZADOR,     # Algoritmo de optimización
    max_iter=MAX_ITER,      # Número máximo de iteraciones
    alpha=ALFA,             # Tasa de aprendizaje.
    random_state=None,      # Semilla para la generación de números aleatorios para reproducibilidad.
    batch_size=TAM_LOTE,    # Tamaño del lote de datos utilizado para la actualización de pesos.
    tol=COTA,               # Tolerancia para la convergencia de parada temprana
    verbose=False            # Imprimir información durante el entrenamiento.
)

# Paso 7: Entrenar el modelo
mlpr.fit(X_train_scaled, y_train)

# Paso 8: Realizar predicciones en el conjunto de prueba
y_pred = mlpr.predict(X_test_scaled)

# Paso 9: Evaluar el modelo
print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))

Matriz de Confusión:
[[ 8  0  1  0  0  0  1]
 [ 0  9  0  0  0  1  0]
 [ 1  0  8  0  0  0  1]
 [ 0  0  0 10  0  0  0]
 [ 0  0  0  0 10  0  0]
 [ 0  0  0  0  0 10  0]
 [ 0  0  2  0  0  0  8]]

Reporte de Clasificación:
              precision    recall  f1-score   support

   BRICKFACE       0.89      0.80      0.84        10
      CEMENT       1.00      0.90      0.95        10
     FOLIAGE       0.73      0.80      0.76        10
       GRASS       1.00      1.00      1.00        10
        PATH       1.00      1.00      1.00        10
         SKY       0.91      1.00      0.95        10
      WINDOW       0.80      0.80      0.80        10

    accuracy                           0.90        70
   macro avg       0.90      0.90      0.90        70
weighted avg       0.90      0.90      0.90        70

